# Generated by Django 3.1 on 2025-07-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Image',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Is_available',
            new_name='is_available',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Stock',
            new_name='stock',
        ),
    ]
