# Generated by Django 3.1 on 2025-07-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account'},
        ),
        migrations.AddField(
            model_name='account',
            name='is_detective',
            field=models.BooleanField(default=False),
        ),
    ]
