# Generated by Django 3.1 on 2025-07-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250716_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_detective',
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
